import { Footer, HeaderNavigation, NavbarTop } from "@/components";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Search . . .",
  description: "Generated by IKI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavbarTop />
        <HeaderNavigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
